# Generated by Django 5.2.17 on 2026-09-13 11:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_mongodb_backend.fields
import meal_voice.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MealLog",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                            ("snack", "Snack"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "logged_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Manual"), ("voice", "Voice")],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("transcript", models.TextField(blank=True, null=True)),
                (
                    "total_macros",
                    models.JSONField(default=meal_voice.models.empty_macros),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-logged_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="MealItem",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "original_text",
                    models.CharField(
                        blank=True,
                        help_text="Verbatim phrase from the transcript.",
                        max_length=255,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("piece", "Piece"),
                            ("bowl", "Bowl"),
                            ("cup", "Cup"),
                            ("plate", "Plate"),
                            ("g", "Gram"),
                            ("ml", "Millilitre"),
                            ("tbsp", "Tablespoon"),
                            ("tsp", "Teaspoon"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "assumed_quantity",
                    models.BooleanField(
                        default=False,
                        help_text="True when no quantity was spoken and 1 serving was assumed.",
                    ),
                ),
                ("macros", models.JSONField(default=meal_voice.models.empty_macros)),
                (
                    "macro_source",
                    models.CharField(
                        choices=[
                            ("table", "Nutrition table"),
                            ("llm_estimate", "LLM estimate"),
                        ],
                        default="llm_estimate",
                        max_length=16,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=1.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "meal_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="meal_voice.meallog",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
